name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter matplotlib numpy scikit-learn cryptography pyinstaller Pillow

      - name: Build Windows Executable
        run: |
          pyinstaller PhenoPlot.spec

      - name: Zip Windows Build Folder
        shell: powershell
        run: |
          Compress-Archive -Path dist/PhenoPlot -DestinationPath PhenoPlot_v1.0_Windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhenoPlot_v1.0_Windows
          path: PhenoPlot_v1.0_Windows.zip
